server:
  port: 8888
  servlet:
    context-path: /api
logging:
  config: classpath:logback-spring.xml

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  main:
    allow-bean-definition-overriding: true
  jackson:
    time-zone: Asia/Shanghai
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      jdbcUrl: jdbc:mysql://localhost:3306/wjdb?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false&rewriteBatchedStatements=true
      username: root
      password: root
      driverClassName: com.mysql.cj.jdbc.Driver
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      filters: stat,wall #\u914D\u7F6E\u8FC7\u6EE4\u5668
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      # 配置DruidStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      # 配置DruidStatViewServlet
      stat-view-servlet:
        url-pattern: "/druid/*"
        # IP白名单(没有配置或者为空，则允许所有访问)
        allow: 127.0.0.1
        # IP黑名单 (存在共同时，deny优先于allow)
        deny: 192.168.1.73
        #  禁用HTML页面上的“Reset All”功能
        reset-enable: false
        # 登录名
        login-username: admin
        # 登录密码
        login-password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://175.24.109.230:3306/jxj_data?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false&rewriteBatchedStatements=true&allowMultiQueries=true
    username: jxj_user
    password: Rxy5i6KCYfArBwN2
  jpa:
    show-sql: false
    database: mysql
    open-in-view: false
  redis:
    host: 127.0.0.1 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    # password: root # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 3000ms # 连接超时时间（毫秒）
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.duoqio.boot.business
mapper:
  not-empty: true
  enum-as-simple-type: true
pagehelper:
  helper-dialect: mysql
  params: count=countSql
  support-methods-arguments: true
  reasonable: falsetitle=Api


swagger:
  title:
  description: Api Documentation
  version: 1.0.0


  name: yangf
  url: http://127.0.0.1/
  email: alooa@qq.com


jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: zc20200422 #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)

xcxwxpay:
  appid: wx4422e690d6579c2c
  secret: 222e0492ae62785ba93bb20eeba850e4
  mchid:
  key:

  projectEnv: dev
  serverDomain: https://127.0.0.1/api

secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /druid/**
#      - /deviceRegist
      - /userLogin
      - /userRegist




#  rabbitmq:
#    host: localhost
#    port: 5672
#    virtual-host: jingxiangjia
#    username: root
#    password: root
#    #开启消息确认模式
#    publisher-confirms: true
#    #开启消息可达监听
#    publisher-returns: true
#    #防止不可达消息被删除
#    template:
#      #开启不可达消息不会被broker给删除
#      mandatory: true
#    # 消费配置
#    listener:
#      simple:
#        concurrency: 5
#        max-concurrency: 10
#        acknowledge-mode: manual
#        prefetch: 1
#        default-requeue-rejected: false
#    #设置连接超时
#    connection-timeout: 1000000

